# Generated by Django 2.2.11 on 2020-03-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papeleria', '0003_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperstore',
            old_name='image_item',
            new_name='image_paper',
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.TextField(default='Sin direccion', max_length=500),
        ),
    ]
