# Generated by Django 2.2.11 on 2020-03-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Papeleria', '0004_auto_20200321_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Papeleria.Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='id_paper_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Papeleria.PaperStore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='Category/None/no-img.jpg', upload_to='Papeleria/static/Category/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_item',
            field=models.ImageField(default='Item/None/no-img.jpg', upload_to='Papeleria/static/Item/'),
        ),
        migrations.AlterField(
            model_name='paperstore',
            name='image_paper',
            field=models.ImageField(default='PaperStore/None/no-img.jpg', upload_to='Papeleria/static/PaperStore/'),
        ),
    ]
